# Select image from https://hub.docker.com/r/_/php/
image: php:7.3

variables:
  COMPOSER_ALLOW_SUPERUSER: 1

unit_test:
  stage: test
  before_script:
    # Install dependencies
    - bash ci/docker_install.sh > /dev/null
  script:
    - touch database/database.sqlite
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - php vendor/bin/phpunit --coverage-text=storage/reports/phpunit_report.txt --colors=never
  artifacts:
    paths:
      - ./storage # for debugging
    expire_in: 1 days

codestyle:
  stage: test
  before_script:
    # Install dependencies
    - bash ci/docker_install.sh > /dev/null
  script:
    - php vendor/bin/phpcs --extensions=php --report=summary --report-file=storage/reports/phpcs.log app
  allow_failure: true # ok if its fails 
  artifacts:
    paths:
      - ./storage # for debugging
    expire_in: 1 days

