# Select image from https://hub.docker.com/r/_/php/
image: php:7.3

stages:
  - test_stage
  - code_analyse_stage

variables:
  COMPOSER_ALLOW_SUPERUSER: 1

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

unit_test:
  stage: test_stage
  script:
    - touch database/database.sqlite
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - php vendor/bin/phpunit --coverage-text=storage/reports/phpunit_report.txt --colors=never
  artifacts:
    paths:
      - ./storage # for debugging
    expire_in: 1 days

codestyle:
  stage: code_analyse_stage
  script:
    - php vendor/bin/phpcs --standard=psr2 --extensions=php --report=full --report-file=storage/reports/phpcs.log app
  allow_failure: true # ok if its fails
  artifacts:
    paths:
      - ./storage # for debugging
    expire_in: 1 days
    when: always

