# Select image from https://hub.docker.com/r/_/php/
image: php:7.3

variables:
  COMPOSER_ALLOW_SUPERUSER: 1

unit_test:
  stage: test
  before_script:
    # Install dependencies
    - bash ci/docker_install.sh > /dev/null
  script:
    - touch database/database.sqlite
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - php vendor/bin/phpunit --coverage-text --colors=never
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

codestyle:
  stage: test
  image: lorisleiva/laravel-docker
  script:
    - phpcs --extensions=php app
  dependencies: []
  allow_failure: true # ok if its fails 
